language: node_js

node_js:
  - "node"

addons:
  sauce_connect: true

before_install:
  # 删除镜像地址
  - rm -f .npmrc
  - npm install -g npm

script:
  - npm run lint
  - npm test

notifications:
  email: false
